### ISSUE TITLE
mixins?

### ISSUE THREAD

**Issue by andyrj** [hyperapp/server#4]
First let me say nice work!  Just made a little branch of my ssr stuff using this and it's very clean.

What's the plan for mixin support?

I think it might be difficult coming at from the angle of interpreting h() directly to strings versus doing a lightweight dom like undom/simple-dom, so you can just "inherit" app() functionality from hyperapp directly.

https://github.com/andyrj/hyperapp-starter/blob/undom/src/server.js#L50

that example should have full mixin support minus any browser specific globals that are accessed that need to be stubbed/mocked from the mixins you choose to use.

I was just wondering what you guys all thought.

**Comment by benjaminj6** [comment]
Oooh that's interesting — makes a lot of sense too. When I did this I was just thinking mainly about simple static HTML rendering so that's why I did strings. However, I will say, this project is kinda on hold for the time being, or at least until the conversation over in `hyperapp/hyperapp` is concluded. In large that's gonna determine the future of what we do here 😎

**Comment by andyrj** [comment]
Ok no problem, sounds good, was just curious if you had something in the works for the server side app() like you had mentioned in the other issue

**Comment by jbucaran** [comment]
For the record #3.

**Comment by JorgeBucaran** [comment]
Mixins are no more (almost).

https://github.com/hyperapp/hyperapp/pull/385

So, closing! :smi
